version: "2"

tasks:
  installDeps:
    desc: Install dependencies
    cmds:
      - pip install --upgrade pip
      - pip3 install --no-cache -r wct_app/requirements.txt

  safetyCheck:
    desc: Run safety check
    cmds:
      - safety check

  lint:
    desc: Lint the app
    dir: wct_app
    cmds:
      - pylint --errors-only **/*.py

  test:
    desc: Test the app
    dir: wct_app
    env:
      SECRET_SAUCE: "{{ default ( randNumeric 1 | add1 ) .SECRET_SAUCE }}"
      WCT_VERSION: 1.2.3
      PATH_TO_DATA_FILE: "data"
    cmds:
      - pytest --disable-warnings --quiet tests/wct_tests.py

  dockerBuild:
    desc: "Build the docker container. You can override the automatic number generation for SECRET_SAUCE by declaring SECRET_SAUCE=<number> after calling the task."
    vars:
      SECRET_SAUCE: "{{ default ( randNumeric 1 | add1 ) .SECRET_SAUCE }}"
      WCT_VERSION: 1.2.3
    cmds:
      - |
        docker build . \
          --build-arg SECRET_SAUCE_ARG="{{ .SECRET_SAUCE }}" \
          --build-arg WCT_VERSION="{{ .WCT_VERSION }}" \
          -t wct-app:local

  loginEcr:
    desc: "Login to ECR"
    silent: true
    cmds:
      - aws ecr get-login --no-include-email | bash

  createRepo:
    desc: "Create an ECR Repo. Usage: task createRepo NAME=<repoName>"
    vars:
      NAME: '{{ default "" .NAME }}'
    cmds:
      - aws ecr create-repository --repository-name "{{ .NAME }}"
    preconditions:
      - sh: test -n "{{ .NAME }}"
        msg: NAME variable not set
    status:
      - aws ecr describe-repositories --repository-names "{{ .NAME }}"

  pushContainer:
    desc: "Push the docker container to the repo"
    vars:
      FULLY_QUALIFIED_IMAGE_NAME: '{{ default "" .FULLY_QUALIFIED_IMAGE_NAME }}'
    cmds:
      - docker tag wct-app:local "{{ .FULLY_QUALIFIED_IMAGE_NAME }}"
      - docker push "{{ .FULLY_QUALIFIED_IMAGE_NAME }}"
    preconditions:
      - sh: test -n "{{ .FULLY_QUALIFIED_IMAGE_NAME }}"
        msg: FULLY_QUALIFIED_IMAGE_NAME not set
